config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'index#index'

  resources :players
  resources :games, only: [:index, :show, :create, :new, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id            :integer          not null, primary key
#  player_one_id :integer
#  player_two_id :integer
#  winner_id     :integer
#  loser_id      :integer
#  state         :string(255)
#  winner_points :integer          default(0)
#  loser_points  :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Game < ApplicationRecord
  include AASM

  belongs_to :player_one, class_name: 'Player'
  belongs_to :player_two, class_name: 'Player'
  belongs_to :winner, class_name: 'Player', optional: true
  belongs_to :loser, class_name: 'Player', optional: true

  scope :by_date, lambda { |date|
    where(updated_at: DateTime.parse(date).beginning_of_day..DateTime.parse(date).end_of_day)
  }
  scope :by_player, lambda { |player|
    id = player.id
    where('player_one_id = ? OR player_two_id = ? OR winner_id = ? OR loser_id = ?', id, id, id, id)
  }

  aasm :state do
    state :active, initial: true
    state :completed

    event :complete do
      transitions to: :completed
    end
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  total_games_count  :integer          default(0), not null
#  win_games_count    :integer          default(0), not null
#  lose_games_count   :integer          default(0), not null
#  win_balls_average  :float(24)        default(0.0), not null
#  lose_balls_average :float(24)        default(0.0), not null
#  weight             :float(24)        default(0.0), not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  balls_count        :float(24)        default(0.0), not null
#

class Player < ApplicationRecord
  validates :name, presence: true

  scope :by_weight, -> { order(weight: :desc) }

  def games(only_wins: false)
    if only_wins
      ::Game.completed.where(winner: self)
    else
      ::Game.by_player(self)
    end
  end

  def last_rivals(count: 2)
    games.order(:updated_at).map do |game|
      game.player_one == self ? game.player_two : game.player_one
    end.last(count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = filtered_games.order(updated_at: :desc)
  end

  def show
    @game = Game.find_by! id: params[:id]
  end

  def create
    result = Games::Create.call(active_players: active_players_ids)

    if result.success?
      redirect_to games_path
    else
      flash[:danger] = result.error
      redirect_to root_path
    end
  end

  def update
    result = Games::Complete.call(player_points.merge(game: Game.find(params[:id])))

    if result.success?
      flash[:success] = 'Game complete!'
    else
      flash[:danger] = result.error
    end

    redirect_to games_path
  end

  private

  def basic_relation
    Game.active.any? ? Game.active : Game.all
  end

  def filtered_games
    player = Player.find_by(name: filter_params)
    player.present? ? basic_relation.by_player(player) : basic_relation
  end

  def filter_params
    return unless params[:player_filter].present?

    params.require(:player_filter)
  end

  def active_players_ids
    params.fetch(:players_ids, {}).keys.map(&:to_i)
  end

  def player_points
    {
      player_one_points: params[:player_one_points].to_i,
      player_two_points: params[:player_two_points].to_i
    }
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  # main page
  def index
    @players = Player.all
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all.by_weight
  end

  def show
    @player = Player.find_by! id: params[:id]
  end

  def create
    player = Player.create! name: params[:name]

    redirect_to players_path
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy!

    redirect_to players_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def correct_active_class(path)
    'activated_link' if path == request.path
  end

  def games_dates(games)
    games.map { |game| game.updated_at.strftime('%d/%m/%Y') }.uniq
  end

  def correct_balls_count_for(player)
    player.total_games_count.zero? ? 0 : (player.balls_count / player.total_games_count).round(2)
  end

  def winner_place_colors(index)
    if Game.completed.count > 10
      case index
        when 0
          'place first-place'
        when 1
          'place second-place'
        when 2
          'place third-place'
        else
          ''
        end
      end
  end

  def list_of_players
    Player.select(:name).order(:name).pluck(:name)
  end
end

app/views/games/_active_games.html.slim
div.games-item
  = form_tag game_path(game), method: :put do
      .thumbnail
        .row
          .col-md-5
            p.text-left="#{game.player_one.name}"
          .col-md-2
            p.text-center VS
          .col-md-5
            p.text-right= "#{game.player_two.name}"
        .row
          .col-md-4
            = text_field_tag 'player_one_points', nil, class: 'form-control'
          .col-md-4.pull-right
            = text_field_tag 'player_two_points', nil, class: 'form-control'
        .row.text-center
          = submit_tag 'Завершить', class: 'btn main_button'
        .row
          p.text-center=  game.created_at.strftime('%d-%m-%Y')

app/views/games/_game_filters.html.slim
= form_tag games_path, role: 'form', method: :get, class: 'form-inline' do
  .form-group
    = select_tag :player_filter, options_for_select(list_of_players), 'data-live-search' => true,
      'data-width' => 'fit', include_blank: true, class: 'form-control selectpicker'
    = submit_tag 'Отфильтровать', class: 'btn main_button', style: 'margin: 10px;'
javascript:
  $(document).ready(function () {
    $('.selectpicker').selectpicker();
  });

app/views/games/_games_table.html.slim
tr
  td.col-md-1= game_counter + 1
  td.col-md-3= game.winner ? game.winner.name : game.player_one.name
  td.col-md-3= game.loser ? game.loser.name : game.player_two.name
  - if with_date == false
    td.col-md-5= "#{game.winner_points}/#{game.loser_points}"
  - else
    td.col-md-2= "#{game.winner_points}/#{game.loser_points}"
    td.col-md-3= game.updated_at.strftime('%d/%m/%Y')

app/views/games/index.html.slim
br
.container
  .row
    .col-md-4.col-md-offset-4
      - if @games.any?
        = render partial: 'game_filters'
  br
  .row.games-list
    - if Game.active.present?
      = render partial: 'active_games', collection: @games, as: :game
    - else
      - games_dates(@games).each do |date|
        h3= 'Дата игр - ' + date
        table.table
          tr
            th #
            th Победитель
            th Проигравший
            th Счёт
          = render partial: 'games_table',
            collection: @games.by_date(date), as: :game, locals: { with_date: false }

app/views/index/_new_games_form.html.slim
.modal-dialog role='document'
  .modal-content
    .modal-header
      h3 Выбери игроков для сегодняшних игр
    .modal-body
      = form_tag games_path do
        table.table.table-hover
          tr
            th Имя
            th Будет играть?
          = render partial: 'players/short_players_table', collection: @players, as: :player
        .modal-footer
          = submit_tag 'Вперёд!', class: 'btn main_button'

app/views/index/index.html.slim
br
.row
  .col-md-6.col-md-offset-3
    .jumbotron
      h3.text-center Привет, теннисисты!
      p.text-center Для генераций игр просто нажмите на кнопку
      p.text-center Если вы ещё не регистрировались, войдите во вкладку Игроки и создайте себя!
      p.text-center
        = link_to 'Начать играть', '', class: 'btn main_button', data: { toggle: 'modal', target: '#new_games_form' }

.modal.fade#new_games_form tabsindex='-1' role='dialog'
  = render 'new_games_form'

app/views/layouts/_header.html.slim
.container
  .header
    .row
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name} alert-dismissable"
          = link_to 'X', '#', class: 'close', data: { dismiss: 'alert' }, aria: { label: 'close' }
          p= msg
    .row
      .col-md-4
        h2.text-center
          = link_to  'Игры', games_path, class: "main_link #{correct_active_class('/games')}"
      .col-md-4.text-center
        = link_to root_path
          = image_tag 'king_pong.png', height: 150, width: 120, style: 'margin-top: 24px; '
      .col-md-4
        h2.text-center
          = link_to 'Игроки', players_path, class: "main_link #{correct_active_class('/players')}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title KingPong (by Bookmate)
    = csrf_meta_tags
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    br
    .container
      == yield

app/views/players/_players_table.html.slim
tr class=winner_place_colors(player_counter)
  td= player_counter + 1
  td= player.weight
  td= link_to player.name, player_path(player), class: 'main_link'
  td= "#{player.total_games_count} (#{player.win_games_count}/#{player.lose_games_count})"
  td= link_to 'Удалить', player_path(id: player.id), method: :delete, class: 'main_link'

app/views/players/_short_players_table.html.slim
tr
  td= player.name
  td
    = check_box_tag "players_ids[#{player.id}]", player.id, false, class: 'checkbox'

app/views/players/index.html.slim
.row
  blockquote
    p
      | Рейтинг игрока высчитывается по формуле, взятой на
      =link_to ' сайте Украинской федерации тенниса ', 'http://reiting.com.ua/rating/about/'
  = link_to 'Добавить нового игрока', new_player_path, class: 'btn main_button pull-right',
    data: { toggle: 'modal', target: '#new_players_form' }
br
.row
  table.table.table-hover
    tr
      th Место
      th Рейтинг
      th Имя
      th Встреч (в/п)
      th Удалить
    = render partial: 'players_table', collection: @players, as: :player

.modal.fade#new_players_form tabsindex='-1' role='dialog'
  .modal-dialog role='document'
    .modal-content
      .modal-header
        h3 Создание нового игрока
      .modal-body
        = form_tag players_path do
          .form-group
            = label_tag :name, 'Введи имя'
            = text_field_tag :name, nil, class: 'form-control'
          .form-group
            = submit_tag 'Создать', class: 'btn main_button'

app/views/players/show.html.slim
.row
  h2= @player.name
  br
  table.table
    tr
      th #
      th Победитель
      th Проигравший
      th Счёт
      th Дата игры
    = render partial: 'games/games_table', collection: @player.games, as: :game, locals: { with_date: true }